### ISSUE TITLE
Decide if +anteroposterior is forward

### ISSUE THREAD

**Issue by ANaaim** [Ipuch/spartacus-shoulder-kinematic-dataset#42]
It seems that we do not agree on this question. We should talk about it. 

For me the
+anteroposterior is forward
+inferosuperior is upward
+mediolateral is pointing on the right

I would be alright to change +anteroposterior to +posteroanterior for the sake of logic ==> but no to -anteroposterior to say forward. (answer to the suggestion on #14 )

todo: 

- [x] change anteroposterior for posteroanterior in sharepoint
- [x] update .csv on github
- [x] update documentation in README.md on github

**Comment by Ipuch** [comment]
Summary of the email exchange:

@ANaaim :

    Pro: Firmly against using "anteroposterior" and suggests using "forward" and "posteroanterior" instead.
    Con: None mentioned.

@fmoissenet :

Raises concerns about the use of "mediolateral" to mean "medio VERS latéral" and "anteroposterior" to mean "posterior VERS anterior" due to terminological inconsistency.

Overall, the main point of contention in the email exchange is the use of terminology related to anatomical directions. Alexandre opposes the use of "anteroposterior" while Florent questions the use of "mediolateral" and "anteroposterior" in certain contexts.

**Comment by Ipuch** [comment]
Also found in Sahara et al. 2006 lateromedial to designate -mediolateral ...
