### ISSUE TITLE
[TO DO] no data for Hallstrom

### ISSUE THREAD

**Issue by Ipuch** [Ipuch/spartacus-shoulder-kinematic-dataset#50]
This is my error message:
> row_data.joint Hallstrom et al. 2006
> ['thorax_x', 'thorax_y', 'thorax_z', 'thorax_origin']  is filled with nan
> ['humerus_x', 'humerus_y', 'humerus_z', 'humerus_origin']  is filled with nan
> ['scapula_x', 'scapula_y', 'scapula_z', 'scapula_origin']  is filled with nan
> ['clavicle_x', 'clavicle_y', 'clavicle_z', 'clavicle_origin']  is filled with nan
> WARNING : euler sequence is nan, for joint glenohumeral Hallstrom et al. 2006
> WARNING : translation is not entirely provided, for joint glenohumeral Hallstrom et al. 2006
> origin_displacement_provided : True
> displacement_cs_provided : False
> Joint glenohumeral has no euler sequence defined,  and no translation defined, it should not be empty !!!
> 

We omited the displacement coordinate system, and the .csv file to the data seems unprovided.
Do we keep this article?

- [ ] waiting for author's response on Euler sequence
- [ ] waiting for author's on translation frame

**Comment by Ipuch** [comment]
I just found that data is provided for that author, it needs a discussion update.

**Comment by fmoissenet** [comment]
In all figures, the horizontal axis corresponds to the glenohumeral motion instead of the humerothoracic motion (range 70°, corresponding to the mean range reporting by the authors for GH joint "The corresponding mean relative maximum abduction of the humerus with the scapula fixed (in the glenohumeral joint) was also similar (70°,range, 57°–93° ...)".

Hence, the data must be removed from the dataset.
